### ISSUE TITLE
adding custom patches to dwl-guile

### ISSUE THREAD

**Issue by crypt17** [engstrand-config/home-service-dwl-guile#10]
I really like the looks of dwl-guile but am new to guix packages in general.

Is there an easy way to add a patch that is not included n your lisf of patches as there are a few things that I would like to add

An example in the readme would be help full if possible

**Comment by Frewacom** [comment]
I think adding custom patches should be as easy as this:

```scheme
(define %patch-mycustompatch
    (local-file "path-to-my-patch.patch"))

(service home-dwl-guile-service-type
         (home-dwl-guile-configuration
           ...
           (patches (list (%patch-mycustompatch)))))
```

`local-file` can be imported by including the `(guix gexp)` module. 

You can find the home service implementation here https://github.com/engstrand-config/home-service-dwl-guile/blob/main/dwl-guile/patches.scm.

**Comment by crypt17** [comment]
It all seems to working nicely. I just need to get the pertag patch applied
now

**Comment by crypt17** [comment]
very nice. I was hoping it would be something like that
