### ISSUE TITLE
dwl-guile crashes when closing foot

### ISSUE THREAD

**Issue by crypt17** [engstrand-config/home-service-dwl-guile#11]
I have found that if I use foot as a terminal with dwl-guile that any time that I close foot dwl-guile will crash. 

This is with the current version of foot from guix

Is this a known issue?

I see no errors show up on the console after the termination so this is a bit confusing.

Alacriity works as expected.

**Comment by Frewacom** [comment]
I also use foot and for me it works fine. However, I have not ran a `guix pull` for a few months, so it could be some issue with the later version of foot.

**Comment by crypt17** [comment]
yeah it is strange. Things work fine until I close foot.

Also I am running guix ontop of.a.debian system so there could be an
interaction there as well.

I need to enable core dumps to see if anything shows up.

**Comment by Frewacom** [comment]
I just ran into the same issue. Unless you have already figured it out, a temporary solution is to downgrade to version 1.11.x of foot.

dwl had quite a large update a few months ago that implements the new wlroots scene graph API, and once dwl-guile pulls in these upstream changes, this issue will be fixed automatically. I have started working on merging the upstream changes with dwl-guile, but there are some quirks left to fix. Some patches also need to be completely reworked, e.g. swallowing.

**Comment by m4lin** [comment]
hello, i am new to guix and dwl-guile, i installed it via guix home and i can see this problem, i was trying to change the default terminal with sakura, but if i use the below it doesent do nothing when i hit the Win+Enter

(config
				(dwl-config (terminal `(,(file-append sakura "/gnu/store/vqq8xqfbvc4xhzvsdfia8f3ffmavifxf-profile/bin/sakura"))))
		    )

what i make wrong?

thanks

Marco

**Comment by Frewacom** [comment]
> hello, i am new to guix and dwl-guile, i installed it via guix home and i can see this problem, i was trying to change the default terminal with sakura, but if i use the below it doesent do nothing when i hit the Win+Enter
> 
> (config (dwl-config (terminal `(,(file-append sakura "/gnu/store/vqq8xqfbvc4xhzvsdfia8f3ffmavifxf-profile/bin/sakura")))) )
> 
> what i make wrong?
> 
> thanks
> 
> Marco

Hi.

You are using the wrong path in `file-append`. Instead of providing the full path to the package in your `/gnu/store`, you only need to write `(file-append sakura "/bin/sakura")`. Make sure to also include the module in which sakura is defined, i.e. `(gnu packages terminals)`, as well as the Guix Gexp package in `(guix gexp)`.  

You can find lots of examples of how to use and configure dwl-guile in [our dotfiles](https://github.com/engstrand-config/guix-dotfiles/blob/main/engstrand/features/wayland.scm).

**Comment by m4lin** [comment]
Thanks.

I will try asap. I did use the full path because if I do whereis sakura I do have only the /gnu/store path.

Will have a look at the config dotfiles as well .

Thanks again

Marco

**Comment by Frewacom** [comment]
foot now works as expected when using the latest version of the home-service.
