### ISSUE TITLE
setq calls aren't properly formatted in the config generated by the guix-home service

### ISSUE THREAD

**Issue by slam-bert** [engstrand-config/home-service-dwl-guile#13]
Hey there!
I'm currently setting up a Guix system, and I wrote a full config for `dwl-guile` by following the instructions in the `README`. 
Unfortunately, I can't start up the `dwl-guile` service if any `setq` commands were used, such as:

* `(setq inhibit-defaults? #t)`
* `(setq border-px 2)`
* `(setq focus-color "#112233")`

Confused, I checked `dwl-guile.log` to find this:

```
guile: uncaught exception
Syntax error:
unknown location: source expression failed to match any pattern in form setq
```

Seeing that nobody else has reported this as an issue, this seems to be a problem on my end.
I did try to use dwl-guile *without* the service, but I just get a segmentation fault whenever I specify my config file.

If there's anything I left out that you need to know, **please** let me know!

**Comment by Frewacom** [comment]
Hi,

That sounds very strange. My initial thought was that dwl-guile's `share/init.scm` were not being loaded correctly, but the error message you are getting indicates that it is. 

I assume you have tried to start dwl-guile with a minimal config containing just a single `setq` call?
If that does not work, you could try to create config file that just starts the `dwl-guile` REPL server, then use e.g. Emacs Geiser to connect to it and attempt to call `setq` that way. I'm pretty sure that will give the same result, but doesn't hurt to try.

**Comment by slam-bert** [comment]
I tried to start `dwl-guile` with only `(setq border-px 2)` in the config.
Like you said, it didn't work.

I also tried using the `dwl-guile` REPL, which happened to work just fine!
I was able to change my border pixel size, my border color, and my focus color with no issues.

Sorry for the late response!

**Comment by slam-bert** [comment]
@Frewacom

I think I found out what the problem has been.

For some reason, `home-service-dwl-guile` formats my config like so:

```
setq
border-px
2
border-color
"#a45a22"
focus-color
"#b75515"
dwl:change-gaps
12
set-keys
"s-d"
'(dwl:spawn "tofi-run")
"s-<return>"
'(dwl:spawn "foot")
"s-j"
'(dwl:focus-stack 1)
"s-k"
'(dwl:focus-stack -1)
"s-l"
'(dwl:change-master-factor 0.05)
"s-h"
'(dwl:change-master-factor -0.05)
"s-<page-up>"
'(dwl:change-masters 1)
"s-<page-down>"
'(dwl:change-masters -1)
"s-t"
'(dwl:cycle-layout 1)
"s-<left>"
'(dwl:focus-monitor 'DIRECTION-LEFT)
"s-<right>"
'(dwl:focus-monitor 'DIRECTION-RIGHT)
"s-<up>"
'(dwl:focus-monitor 'DIRECTION-UP)
"s-<down>"
'(dwl:focus-monitor 'DIRECTION-DOWN)
"s-S-<left>"
'(dwl:tag-monitor 'DIRECTION-LEFT)
"s-S-<right>"
'(dwl:tag-monitor 'DIRECTION-RIGHT)
"s-S-<up>"
'(dwl:tag-monitor 'DIRECTION-UP)
"s-S-<down>"
'(dwl:tag-monitor 'DIRECTION-DOWN)
"s-q"
'dwl:kill-client
"s-<space>"
'dwl:zoom
"s-<tab>"
'dwl:view
"s-S-0"
'(dwl:view 0)
"s-f"
'dwl:toggle-fullscreen
"S-s-<space>"
'dwl:toggle-floating
"S-s-<escape>"
'dwl:quit
"<XF86PowerOff>"
'dwl:quit
"s-<mouse-left>"
'dwl:move
"s-<mouse-middle>"
'dwl:toggle-floating
"s-<mouse-right>"
'dwl:resize
dwl:set-tag-keys
"s"
"s-S"
dwl:set-tty-keys
"C-M"
dwl:start-repl-server
setq
inhibit-defaults?
#t
```

When I typed it out like this in my `guix-home` config:

```
(setq inhibit-defaults? #t)
(dwl:start-repl-server)
(dwl:set-tty-keys "C-M")
(dwl:set-tag-keys "s" "s-S")
(set-keys "s-d" '(dwl:spawn "tofi-run")
	  "s-<return>" '(dwl:spawn "foot")
	  "s-j" '(dwl:focus-stack 1)
	  "s-k" '(dwl:focus-stack -1)
	  "s-l" '(dwl:change-master-factor 0.05)
	  "s-h" '(dwl:change-master-factor -0.05)
	  "s-<page-up>" '(dwl:change-masters 1)
	  "s-<page-down>" '(dwl:change-masters -1)
	  "s-t" '(dwl:cycle-layout 1)
	  "s-<left>" '(dwl:focus-monitor 'DIRECTION-LEFT)
	  "s-<right>" '(dwl:focus-monitor 'DIRECTION-RIGHT)
	  "s-<up>" '(dwl:focus-monitor 'DIRECTION-UP)
	  "s-<down>" '(dwl:focus-monitor 'DIRECTION-DOWN)
	  "s-S-<left>" '(dwl:tag-monitor 'DIRECTION-LEFT)
	  "s-S-<right>" '(dwl:tag-monitor 'DIRECTION-RIGHT)
	  "s-S-<up>" '(dwl:tag-monitor 'DIRECTION-UP)
	  "s-S-<down>" '(dwl:tag-monitor 'DIRECTION-DOWN)
	  "s-q" 'dwl:kill-client
	  "s-<space>" 'dwl:zoom
	  "s-<tab>" 'dwl:view
	  "s-S-0" '(dwl:view 0) ;; 0 will show all tags
	  "s-f" 'dwl:toggle-fullscreen
	  "S-s-<space>" 'dwl:toggle-floating
	  "S-s-<escape>" 'dwl:quit
	  "<XF86PowerOff>" 'dwl:quit
	  "s-<mouse-left>" 'dwl:move
	  "s-<mouse-middle>" 'dwl:toggle-floating
	  "s-<mouse-right>" 'dwl:resize)
(dwl:change-gaps 12)
(setq border-px 2
      border-color "#a45a22"
      focus-color "#b75515")
```

From what I can infer, the `config.scm` file generated by the service formats `setq` calls to not have parenthesis, which is a syntax error. This explains the error I was getting from `dwl-guile.log`.

**Comment by Frewacom** [comment]
Ah that makes sense, though I am not sure there is any issue with the serializer. What does your Guix home configuration look like?

**Comment by slam-bert** [comment]
I'm sorry for the **very** late response!

I found a fix by making my configuration a list:

```
(config
  (list
    '(...))
```

I'd recommend updating `README.org` to include this, as it makes sure that `~/.config/dwl-guile/config.scm` is formatted correctly after the home config is built.

**Comment by Frewacom** [comment]
No problem!

Yeah, that's what I thought was the issue. I should definitely make that clear in the README, and it should be possible to verify this in the home service during reconfiguration as well.
