### ISSUE TITLE
Applying the Xwayland patch  

### ISSUE THREAD

**Issue by Arian-D** [engstrand-config/home-service-dwl-guile#15]
Hi, I have two questions:
1. I tried following the example in the comment which was `(patch-dwl-guile-package dwl-guile #:patches '(%patch-xwayland))` and that gave me the following error:
```scheme
Backtrace:
In guix/store.scm:
   1996:8 19 (_ _)
In guix/gexp.scm:
   299:22 18 (_ _)
In guix/store.scm:
   1996:8 17 (_ _)
In guix/packages.scm:
  1971:11 16 (_ _)
In guix/gexp.scm:
   1180:2 15 (_ #<store-connection 256.99 ffff71e59280>)
   1046:2 14 (_ _)
    892:4 13 (_ _)
In guix/store.scm:
  2053:12 12 (_ #<store-connection 256.99 ffff71e59280>)
  1380:11 11 (map/accumulate-builds #<store-connection 256.99 ffff7…> …)
   1298:8 10 (call-with-build-handler #<procedure ffff71539f30 at g…> …)
  2168:25  9 (run-with-store #<store-connection 256.99 ffff71e59280> …)
In guix/gexp.scm:
   897:13  8 (_ _)
In guix/store.scm:
   1996:8  7 (_ _)
In guix/gexp.scm:
   299:22  6 (_ _)
In guix/packages.scm:
   2092:7  5 (_ _)
   954:17  4 (patch-and-repack #<derivation /gnu/store/xjwdca6bp36w…> …)
In srfi/srfi-1.scm:
   586:17  3 (map1 (%patch-xwayland))
In guix/packages.scm:
    940:4  2 (instantiate-patch _)
In ice-9/boot-9.scm:
  1685:16  1 (raise-exception _ #:continuable? _)
  1685:16  0 (raise-exception _ #:continuable? _)

ice-9/boot-9.scm:1685:16: In procedure raise-exception:
Throw to key `match-error' with args `("match" "no matching pattern" %patch-xwayland)'.
```
which made me think that I might need the value rather than the `'%patch-xwayland` symbol. Changing it to `(list %patch-xwayland)` got rid of the error. Is that right, or should it be a symbol that I'm not importing?

2. My current service definition is
```scheme
(service home-dwl-guile-service-type
                 (home-dwl-guile-configuration
                  (package
                   (patch-dwl-guile-package dwl-guile
                                            #:patches (list %patch-xwayland)))
                  (reload-config-on-change? #t)))
```
Wayland apps work fine, but X apps still do not launch. Do I need to do any extra steps?

**Comment by Frewacom** [comment]
It should **not** be a symbol, so your approach is correct. There should not be any additional steps required for XWayland to work. I'll fix the typo in the README, thanks. 

What X apps did you try to launch? Any errors if you run them in the terminal?

**Comment by Arian-D** [comment]
Thank you for the swift reply and fixing the documentation.

I had been trying `guix shell xeyes -- xeyes` and it kept failing. I added `%patch-movestack` to the list and now it magically works. I'm not sure what was causing the issue, so I'll just close this.
