### ISSUE TITLE
extraneous field initializers (tty-number)

### ISSUE THREAD

**Issue by brandhout** [engstrand-config/home-service-dwl-guile#5]
Hi!

The standard configuration works in a vanilla guix installation when I start dwl-guile with `dwl-guile -c %config path%`. besides this build time error:
`Loading /gnu/store/wnfrnn1ax6sfqxlpg2hk8mfdijmpphic-shepherd.conf.
herd: exception caught while executing 'load' on service 'root':`
nice! 

When I want to auto-start dwl-guile on a tty with the 
`(service home-dwl-guile-service-type
  (home-dwl-guile-configuration
    (tty-number 2)
    (native-qt? #t))))))` directive in my home config the following error is produced on build-time:
`couldn't create backend
xxxx@guix_gnu ~$ guix home reconfigure src/guix-config/home-configuration.scm
/home/xxxx/src/guix-config/home-configuration.scm:39:2: error: (%home-dwl-guile-configuration (tty-number 2) (native-qt? #t)): extraneous field initializers (tty-number)`

Is this a bug or am I missing something ? Thanks.

**Comment by Frewacom** [comment]
Not a bug, just me being lazy. The documentation in the README is not updated. The currently available options can be seen here:
https://github.com/engstrand-config/home-service-dwl-guile/blob/dab5118324127c9d251d20007da14af2e3448973/dwl-guile/home-service.scm#L78-L113

The TTY-option has been removed to simplify things a bit, but I'll consider re-adding it if that is a feature that you want/need.  

Edit: also note that the `auto-start?` option currently does nothing. dwl-guile will auto-start by Shepherd on whatever TTY you login to first.

**Comment by brandhout** [comment]
Thanks, I do not need the `tty-number` option, since I wasn't aware of the current auto-start. Works great! 

I might create a pull request to the documentation later today with the small documentation fix.
