### ISSUE TITLE
Rewrite configuration into an Emacs-like configuration

### ISSUE THREAD

**Issue by Frewacom** [engstrand-config/home-service-dwl-guile#9]
The current configuration is too complex and is essentially unusable without using the home service. A much better option would be to implement an Emacs-like approach to the configuration, where variables can be set/unset/updated using something like `setq`. 

Obviously, it should not be anywhere near as advanced as Emacs, but it should support the most basic operations. A config for dwl-guile might look like this:
```scheme
`((setq border-px 2)
  (setq root-color "#FFFFFF")
  (global-set-key 
    (kbd "C-s-<enter>")
    (lambda () (...)))
  (...))
```

**Comment by crypt17** [comment]
I really like it being in scheme but it would be nice to have some sort of repl like you have with stumpwm where you can test changes dynaically

**Comment by Frewacom** [comment]
> I really like it being in scheme but it would be nice to have some sort of repl like you have with stumpwm where you can test changes dynaically

Yes, that is one of the primary reasons for implementing this

**Comment by crypt17** [comment]
This feels like a nice direction to head in. So far I am enjoying this so
much more than dwl/dwm it seems to have a better balance of features with
customizability
